name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Sanity
      run: npm run sanity:setup
      env:
        SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        
    - name: Import content
      run: npm run sanity:import
      env:
        SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        
    - name: Build application
      run: npm run build
      env:
        VITE_SANITY_PROJECT_ID: ${{ secrets.VITE_SANITY_PROJECT_ID }}
        VITE_SANITY_DATASET: ${{ secrets.VITE_SANITY_DATASET }}
        VITE_SANITY_TOKEN: ${{ secrets.VITE_SANITY_TOKEN }}
        
    - name: Deploy Sanity Studio
      run: npm run sanity:deploy
      env:
        SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        
    # Add deployment to your hosting platform here
    # Example for Vercel:
    # - name: Deploy to Vercel
    #   uses: amondnet/vercel-action@v25
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     vercel-org-id: ${{ secrets.ORG_ID }}
    #     vercel-project-id: ${{ secrets.PROJECT_ID }}
    #     vercel-args: '--prod' 